# Copyright (c) 2025-2026 Netresearch DTT GmbH
# SPDX-License-Identifier: GPL-2.0-or-later

services:
  web:
    build:
      args:
        GIT_BRANCH: "unknown"
        GIT_COMMIT: "unknown"
        GIT_PR: "unknown"
